import { db } from "@workspace/db";
import { carsTable, notificationsTable } from "@workspace/db/schema";

const carImages = {
  suv: [
    "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
    "https://images.unsplash.com/photo-1551522435-a13afa10f103?w=800&q=80",
    "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
  ],
  sports: [
    "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
    "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800&q=80",
  ],
  luxury: [
    "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
    "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
  ],
  economy: [
    "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
    "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=800&q=80",
    "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
  ],
  truck: [
    "https://images.unsplash.com/photo-1590496793929-36417d3117de?w=800&q=80",
    "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=800&q=80",
  ],
  electric: [
    "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80",
    "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&q=80",
  ],
};

const sellers = [
  {
    id: "seller-001",
    name: "Miguel Hernández",
    phone: "+52 55 1234 5678",
    whatsapp: "+52 55 1234 5678",
    rating: 4.8,
    totalListings: 12,
    memberSince: "2022",
    avatar: null,
  },
  {
    id: "seller-002",
    name: "Ana García",
    phone: "+52 33 9876 5432",
    whatsapp: "+52 33 9876 5432",
    rating: 4.6,
    totalListings: 7,
    memberSince: "2023",
    avatar: null,
  },
  {
    id: "seller-003",
    name: "AutoMex Premium",
    phone: "+52 81 5555 1234",
    whatsapp: "+52 81 5555 1234",
    rating: 4.9,
    totalListings: 45,
    memberSince: "2020",
    avatar: null,
  },
  {
    id: "seller-004",
    name: "Rodrigo Torres",
    phone: "+52 55 8765 4321",
    whatsapp: "+52 55 8765 4321",
    rating: 4.3,
    totalListings: 3,
    memberSince: "2024",
    avatar: null,
  },
];

const seedCars = [
  {
    title: "BMW X5 xDrive40i 2022",
    price: "895000",
    lat: "19.4326",
    lng: "-99.1332",
    address: "Polanco, Ciudad de México",
    city: "Ciudad de México",
    images: carImages.suv,
    specs: {
      brand: "BMW",
      model: "X5 xDrive40i",
      year: 2022,
      km: 28000,
      transmission: "automatic" as const,
      fuel: "gasoline" as const,
      color: "Blanco",
      doors: 5,
      horsepower: 340,
      engine: "3.0L Turbo",
    },
    description: "BMW X5 en perfectas condiciones, único dueño, con garantía de agencia vigente hasta 2024. Equipado con paquete M Sport, techo solar panorámico, asientos de piel calefaccionados y sistema de audio Harman Kardon. Mantenimientos al corriente en agencia.",
    seller: sellers[2]!,
    tags: ["único dueño", "garantía", "impecable"],
    category: "suv",
    status: "active" as const,
    featured: true,
    badge: "destacado" as const,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Porsche 911 Carrera 2021",
    price: "2450000",
    lat: "19.4200",
    lng: "-99.1750",
    address: "Santa Fe, Ciudad de México",
    city: "Ciudad de México",
    images: carImages.sports,
    specs: {
      brand: "Porsche",
      model: "911 Carrera",
      year: 2021,
      km: 15000,
      transmission: "automatic" as const,
      fuel: "gasoline" as const,
      color: "Rojo Carmín",
      doors: 2,
      horsepower: 385,
      engine: "3.0L Flat-6 Turbo",
    },
    description: "Porsche 911 Carrera en estado impecable. Sport Chrono Package, PDK de 8 velocidades, asientos sport plus, PDLS+. Una experiencia de conducción inigualable. Disponible para prueba de manejo con cita previa.",
    seller: sellers[0]!,
    tags: ["deportivo", "poco uso", "lujo"],
    category: "deportivo",
    status: "active" as const,
    featured: true,
    badge: "destacado" as const,
    isFavorited: true,
    hasVideo: false,
  },
  {
    title: "Toyota Corolla 2023 Híbrido",
    price: "385000",
    lat: "20.6597",
    lng: "-103.3496",
    address: "Guadalajara Centro, Jalisco",
    city: "Guadalajara",
    images: carImages.electric,
    specs: {
      brand: "Toyota",
      model: "Corolla Híbrido",
      year: 2023,
      km: 8500,
      transmission: "cvt" as const,
      fuel: "hybrid" as const,
      color: "Gris Plata",
      doors: 4,
      horsepower: 122,
      engine: "1.8L Híbrido",
    },
    description: "Toyota Corolla híbrido casi nuevo, primer dueño, sin accidentes. Excelente rendimiento de combustible, promedio 22 km/l. Pantalla táctil, cámara de reversa, Toyota Safety Sense. Ideal para uso diario.",
    seller: sellers[1]!,
    tags: ["híbrido", "nuevo", "eficiente"],
    category: "nuevo",
    status: "active" as const,
    featured: false,
    badge: "nuevo" as const,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Ford Ranger XLT 2022",
    price: "520000",
    lat: "25.6866",
    lng: "-100.3161",
    address: "San Pedro Garza García, Nuevo León",
    city: "Monterrey",
    images: carImages.truck,
    specs: {
      brand: "Ford",
      model: "Ranger XLT",
      year: 2022,
      km: 42000,
      transmission: "automatic" as const,
      fuel: "diesel" as const,
      color: "Blanco Oxford",
      doors: 4,
      horsepower: 170,
      engine: "2.2L Diesel",
    },
    description: "Ford Ranger XLT doble cabina, diesel, tracción 4x4. Perfecto para trabajo y aventura. Caja de carga con cubierta, llantas BFGoodrich AT, sistema de frenos ABS, 7 bolsas de aire. Excelente estado.",
    seller: sellers[3]!,
    tags: ["trabajo", "4x4", "diesel"],
    category: "trabajo",
    status: "active" as const,
    featured: false,
    badge: null,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Volkswagen Jetta 2021",
    price: "285000",
    lat: "19.0400",
    lng: "-98.2063",
    address: "Puebla Centro, Puebla",
    city: "Puebla",
    images: carImages.economy,
    specs: {
      brand: "Volkswagen",
      model: "Jetta",
      year: 2021,
      km: 52000,
      transmission: "automatic" as const,
      fuel: "gasoline" as const,
      color: "Azul Denim",
      doors: 4,
      horsepower: 147,
      engine: "1.4L TSI",
    },
    description: "Volkswagen Jetta en muy buen estado, mantenimiento en agencia VW. Pantalla Discover Media, sensores de estacionamiento, App-Connect. Precio negociable, acepto auto a cuenta.",
    seller: sellers[1]!,
    tags: ["económico", "ciudad", "buen precio"],
    category: "economico",
    status: "active" as const,
    featured: false,
    badge: "oferta" as const,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Mercedes-Benz GLE 400 2023",
    price: "1450000",
    lat: "19.4350",
    lng: "-99.1900",
    address: "Lomas de Chapultepec, CDMX",
    city: "Ciudad de México",
    images: carImages.luxury,
    specs: {
      brand: "Mercedes-Benz",
      model: "GLE 400",
      year: 2023,
      km: 12000,
      transmission: "automatic" as const,
      fuel: "gasoline" as const,
      color: "Negro Obsidiana",
      doors: 5,
      horsepower: 367,
      engine: "3.0L Biturbo",
    },
    description: "Mercedes-Benz GLE 400 4MATIC de agencia, prácticamente nuevo. Equipado con AMG Line, asientos Nappa, sistema MBUX con pantalla de 12.3\", Burmester 3D, techo solar. El lujo y la tecnología en su máxima expresión.",
    seller: sellers[2]!,
    tags: ["lujo", "garantía", "premium"],
    category: "lujo",
    status: "active" as const,
    featured: true,
    badge: "destacado" as const,
    isFavorited: true,
    hasVideo: false,
  },
  {
    title: "Honda CR-V 2022",
    price: "445000",
    lat: "20.9674",
    lng: "-89.6237",
    address: "Mérida Norte, Yucatán",
    city: "Mérida",
    images: [...carImages.suv].reverse(),
    specs: {
      brand: "Honda",
      model: "CR-V",
      year: 2022,
      km: 31000,
      transmission: "cvt" as const,
      fuel: "gasoline" as const,
      color: "Rojo Radiant",
      doors: 5,
      horsepower: 190,
      engine: "1.5L Turbo",
    },
    description: "Honda CR-V Touring en impecables condiciones. Tracción AWD, asientos de cuero con ventilación, Head-up Display, Honda Sensing completo, techo panorámico. Primer dueño, sin accidentes, todo original.",
    seller: sellers[0]!,
    tags: ["familiar", "seguro", "AWD"],
    category: "suv",
    status: "active" as const,
    featured: false,
    badge: null,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Nissan Sentra SR 2023",
    price: "265000",
    lat: "19.5438",
    lng: "-99.1735",
    address: "Ecatepec, Estado de México",
    city: "Ciudad de México",
    images: carImages.economy,
    specs: {
      brand: "Nissan",
      model: "Sentra SR",
      year: 2023,
      km: 5200,
      transmission: "cvt" as const,
      fuel: "gasoline" as const,
      color: "Blanco Perla",
      doors: 4,
      horsepower: 149,
      engine: "2.0L",
    },
    description: "Nissan Sentra SR prácticamente nuevo, sin detalles. Versión tope de línea con pantalla de 8\", cámara 360°, Intelligent Emergency Braking, navegación integrada. Factura de agencia, primera mano.",
    seller: sellers[3]!,
    tags: ["nuevo", "primer dueño", "económico"],
    category: "economico",
    status: "active" as const,
    featured: false,
    badge: "nuevo" as const,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Audi A4 Avant 2020",
    price: "520000",
    lat: "20.6674",
    lng: "-103.3942",
    address: "Zapopan, Jalisco",
    city: "Guadalajara",
    images: [...carImages.luxury].slice(0, 2),
    specs: {
      brand: "Audi",
      model: "A4 Avant",
      year: 2020,
      km: 68000,
      transmission: "automatic" as const,
      fuel: "gasoline" as const,
      color: "Gris Manhattan",
      doors: 5,
      horsepower: 190,
      engine: "2.0L TFSI",
    },
    description: "Audi A4 Avant en excelente estado general. Quattro AWD, Virtual Cockpit, Bang & Olufsen, techo solar. Mantenimientos en agencia hasta los 65,000 km. Ligera baja en precio por viaje, acepto propuestas serias.",
    seller: sellers[1]!,
    tags: ["lujo", "familiar", "AWD"],
    category: "lujo",
    status: "active" as const,
    featured: false,
    badge: "oferta" as const,
    isFavorited: false,
    hasVideo: false,
  },
  {
    title: "Tesla Model 3 2022",
    price: "875000",
    lat: "25.6714",
    lng: "-100.3061",
    address: "Valle Oriente, Monterrey",
    city: "Monterrey",
    images: carImages.electric,
    specs: {
      brand: "Tesla",
      model: "Model 3",
      year: 2022,
      km: 22000,
      transmission: "automatic" as const,
      fuel: "electric" as const,
      color: "Azul Medianoche",
      doors: 4,
      horsepower: 350,
      engine: "Eléctrico Dual Motor",
    },
    description: "Tesla Model 3 Long Range AWD en perfectas condiciones. Autopilot completo, Full Self-Driving (transferible), cargador instalado en casa incluido. 550 km de autonomía real. El futuro de la conducción, hoy.",
    seller: sellers[2]!,
    tags: ["eléctrico", "tecnología", "autopilot"],
    category: "nuevo",
    status: "active" as const,
    featured: true,
    badge: "destacado" as const,
    isFavorited: false,
    hasVideo: false,
  },
];

const seedNotifications = [
  {
    type: "new_car",
    title: "Nuevo auto en tu zona",
    message: "Se publicó un BMW X5 2022 en Polanco, Ciudad de México",
    carId: null,
    read: false,
  },
  {
    type: "price_drop",
    title: "Bajó el precio",
    message: "El Audi A4 Avant que guardaste bajó $30,000 pesos",
    carId: null,
    read: false,
  },
  {
    type: "new_message",
    title: "Nuevo mensaje",
    message: "Miguel Hernández te escribió sobre el Porsche 911",
    carId: null,
    read: true,
  },
  {
    type: "system",
    title: "Bienvenido a AutoSpot",
    message: "Completa tu perfil para recibir alertas personalizadas de autos",
    carId: null,
    read: true,
  },
  {
    type: "price_drop",
    title: "Oferta especial",
    message: "El Volkswagen Jetta 2021 en Puebla tiene una oferta especial hoy",
    carId: null,
    read: false,
  },
];

async function seed() {
  console.log("Seeding AutoSpot database...");

  await db.delete(notificationsTable);
  await db.delete(carsTable);

  const insertedCars = await db.insert(carsTable).values(seedCars).returning();
  console.log(`Inserted ${insertedCars.length} cars`);

  const notifWithCarIds = seedNotifications.map((n, i) => ({
    ...n,
    carId: i < 3 ? insertedCars[i]?.id ?? null : null,
  }));

  const insertedNotifs = await db.insert(notificationsTable).values(notifWithCarIds).returning();
  console.log(`Inserted ${insertedNotifs.length} notifications`);

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
