import { pgTable, serial, text, numeric, boolean, integer, timestamp, jsonb } from "drizzle-orm/pg-core";

export const partnersTable = pgTable("partners", {
  id: serial("id").primaryKey(),
  businessName: text("business_name").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  address: text("address").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull(),
  googleMapsUrl: text("google_maps_url"),
  lat: numeric("lat", { precision: 10, scale: 6 }),
  lng: numeric("lng", { precision: 10, scale: 6 }),
  phone: text("phone").notNull(),
  whatsapp: text("whatsapp"),
  email: text("email"),
  website: text("website"),
  ownerName: text("owner_name").notNull(),
  ownerPhone: text("owner_phone").notNull(),
  ownerEmail: text("owner_email").notNull(),
  images: jsonb("images").$type<string[]>().default([]),
  logo: text("logo"),
  discountPercent: integer("discount_percent").notNull().default(10),
  discountDescription: text("discount_description"),
  discountCode: text("discount_code"),
  conversionFee: numeric("conversion_fee", { precision: 5, scale: 2 }).default("5"),
  adFeePaid: boolean("ad_fee_paid").default(false),
  adFeeAmount: numeric("ad_fee_amount", { precision: 8, scale: 2 }).default("20"),
  complementarios: text("complementarios"),
  rating: numeric("rating", { precision: 3, scale: 2 }).default("0"),
  reviewCount: integer("review_count").default(0),
  featured: boolean("featured").default(false),
  status: text("status").notNull().default("pending"),
  rejectionReason: text("rejection_reason"),
  approvedAt: timestamp("approved_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
